# Generated by Django 3.1.5 on 2021-01-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_groceryitem_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
